package com.itemis.mgttg.controller;

public enum ResultCode {
    OK,
    TRANSLATION_ANSWER,
    PRICE_ANSWER,
    LIST_MATERIALS,
    LIST_WORDS,
    WORD_ALREADY_KNOWN,
    MATERIAL_ALREADY_KNOWN,
    ALIEN_WORD_UNKNOWN,
    DIDNT_UNDERSTAND_LINE,
    ROMAN_NUMERAL_INVALID,
    HELP;
}
